-- begin SAMPLE_ORDERalter table SAMPLE_ORDER add constraint FK_SAMPLE_ORDER_CUSTOMER_ID foreign key (CUSTOMER_ID) references SAMPLE_CUSTOMER(ID)^
create index IDX_SAMPLE_ORDER_CUSTOMER on SAMPLE_ORDER (CUSTOMER_ID)^
-- end SAMPLE_ORDER
-- begin SAMPLE_ORDER_LINE
alter table SAMPLE_ORDER_LINE add constraint FK_SAMPLE_ORDER_LINE_ORDER_ID foreign key (ORDER_ID) references SAMPLE_ORDER(ID)^
alter table SAMPLE_ORDER_LINE add constraint FK_SAMPLE_ORDER_LINE_PRODUCT_ID foreign key (PRODUCT_ID) references SAMPLE_PRODUCT(ID)^
create index IDX_SAMPLE_ORDER_LINE_ORDER on SAMPLE_ORDER_LINE (ORDER_ID)^
create index IDX_SAMPLE_ORDER_LINE_PRODUCT on SAMPLE_ORDER_LINE (PRODUCT_ID)^
-- end SAMPLE_ORDER_LINE
-- begin SAMPLE_PRODUCT
alter table SAMPLE_PRODUCT add constraint FK_SAMPLE_PRODUCT_CUSTOMER_ID foreign key (CUSTOMER_ID) references SAMPLE_CUSTOMER(ID)^
create index IDX_SAMPLE_PRODUCT_CUSTOMER on SAMPLE_PRODUCT (CUSTOMER_ID)^
-- end SAMPLE_PRODUCT
-- begin SAMPLE_TERMINAL
alter table SAMPLE_TERMINAL add constraint FK_SAMPLE_TERMINAL_AIRPORT foreign key (AIRPORT_ID) references SAMPLE_AIRPORT(ID)^
create index IDX_SAMPLE_TERMINAL_AIRPORT on SAMPLE_TERMINAL (AIRPORT_ID)^
-- end SAMPLE_TERMINAL
-- begin SAMPLE_MEETING_POINT
alter table SAMPLE_MEETING_POINT add constraint FK_SAMPLE_MEETING_POINT_TERMINAL foreign key (TERMINAL_ID) references SAMPLE_TERMINAL(ID)^
create index IDX_SAMPLE_MEETING_POINT_TERMINAL on SAMPLE_MEETING_POINT (TERMINAL_ID)^
-- end SAMPLE_MEETING_POINT
-- begin SAMPLE_NOTE
alter table SAMPLE_NOTE add constraint FK_SAMPLE_NOTE_MEETING_POINT foreign key (MEETING_POINT_ID) references SAMPLE_MEETING_POINT(ID)^
create index IDX_SAMPLE_NOTE_MEETING_POINT on SAMPLE_NOTE (MEETING_POINT_ID)^
-- end SAMPLE_NOTE
